### ISSUE TITLE
Should we add boilerplate?

### ISSUE THREAD

**Issue by remyoudemans** [oodlefinance/front-end-technical-test#2]
Do we care about a candidate showing that they know how to use create-react-app? I would guess no, so I reckon we should add the boilerplate so they can get right into the juicy stuff.

I say we provide an empty app using our react framework and our css-in-js framework. That way we're advertising that we use nice new tech as well!

**Comment by AMoreton** [comment]
I'm absolutely in favour of this. I'm not concerned with whether or not a candidate can use CRA, I'm more interested in how they solve the problem. Also, if we provide the boilerplate it will give us a baseline with which to better compare/contrast solutions.
